# Generated by Django 4.1.1 on 2022-09-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("pw", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
            ],
            options={"db_table": "user", "managed": False,},
        ),
    ]
